<?php

namespace AppBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProvince(){
        $query = $this->createQueryBuilder('c')
            ->where('c.code like :code')
            ->setParameters(['code'=>'%0000'])
        ;
        return $query;
    }

    public function getCity($code){
        return $this->createQueryBuilder('c')
            ->where('c.code like :code')
            ->setParameters(['code'=>"$code%00"]);
    }

    public function getArea($code){
        return $this->createQueryBuilder('c')
            ->where('c.code like :code')
            ->setParameters(['code'=>"$code%"]);
    }
}
