<?php

namespace AppBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProvince(){
        $query = $this->createQueryBuilder('c')
            ->where('c.code like :code')
            ->setParameters(['code'=>'%0000'])
        ;
        return $query;
    }

    public function getCity($code){
        if(null == $code){
            return null;
        }
        $query = $this->createQueryBuilder('c');
        if($this->isGovernment($code)){
            $query->where('c.code = :code')
                ->setParameters([
                    'code'=>$code."0000",
                ]);
        }else{
            $query->where('c.code like :code')
                ->andWhere('c.code != :code2')
                ->setParameters([
                    'code'=>"$code%00",
                    'code2'=>$code."0000",
                ]);
        }

        return $query;
    }

    public function getArea($code){
        if(null == $code){
            return null;
        }
        $query = $this->createQueryBuilder('c');
        $gmCode = substr($code,0,2);
        if($this->isGovernment($gmCode)){
            $query->where('c.code like :code')
                ->setParameters([
                    'code'=>"$gmCode%",
                ]);
        }else{
            $query->where('c.code like :code')
                ->andWhere('c.code != :code2')
                ->setParameters([
                    'code'=>"$code%",
                    'code2'=>$code.'00',
                ]);
        }
        return $query;
    }

    public function isGovernment($code){
        if('11' == $code || '31' == $code || '50' == $code || '12' == $code){
            return true;
        }
        return false;
    }
}
