<?php

namespace AppBundle\Repository;

/**
 * GoodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProvider($id){
        $query = $this->createQueryBuilder('g')
            ->join('g.goodsDetail','d','WITH')
            ->join('d.product','p','WITH')
            ->where('p.provider = :id')
            ->andWhere('g.providerRead = false')
            ->andWhere('g.status = 1')
            ->setParameter('id',$id)
            ->getQuery()
            ;
        return $query->getResult();
    }
}
