<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMax($num, array $order){
        $query = $this->createQueryBuilder('p')
            ->orderBy($order[0],$order[1])
            ->getQuery()
        ;
        return $query->getMaxResults($num);
    }
}
