<?php

namespace AppBundle\Repository;

/**
 * SingleStradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SingleStradeRepository extends \Doctrine\ORM\EntityRepository
{
}
