<?php

namespace AppBundle\Repository;

/**
 * SwipperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SwipperRepository extends \Doctrine\ORM\EntityRepository
{
}
