ivory_ck_editor:
    input_sync: true
    default_config: advanced_config
    configs:
        base_config:
            filebrowserImageUploadUrl: '/uploads/images/'
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'BulletedList', 'Link'] }
        advanced_config:
            filebrowserImageUploadUrl: '/uploads/images/'
            toolbar: full