imports:
    - { resource: 'easy_admin/' }
easy_admin:
    site_name: '管理系统'
    design:
        menu:
            - {entity: 'Settings', label: '网站设置'}
            - {entity: 'User', label: '网站管理员'}
            - {entity: 'Member', label: '会员管理'}
            - {entity: 'Provider', label: '商家管理'}
            - {entity: 'Product', label: '服装管理'}
            - {entity: 'Goods', label: '订单管理'}
            - {entity: 'Coupon', label: '礼券管理'}
            - {entity: 'Company', label: '品牌信息'}
            - {entity: 'Contact', label: '联系信息'}
            - label: '网站首页'
              children:
                - { entity: 'Swipper', label: '幻灯片管理' }