imports:
    - { resource: 'easy_admin/' }
easy_admin:
    site_name: '管理系统'
    formats:
        date: 'Y年m月d日'
        time: 'H:i:s'
        datetime: 'Y年m月d日H:i:s'
    design:
        menu:
            - {entity: 'Settings', label: '网站设置'}
            - {entity: 'Menu', label: '网站菜单'}
            - {entity: 'Product', label: '服装管理'}
            - {entity: 'Goods', label: '订单管理'}
            - {entity: 'Coupon', label: '礼券管理'}
            - {entity: 'Company', label: '品牌信息'}
            - {entity: 'Contact', label: '联系信息'}
            - label: '网站首页'
              children:
                - { entity: 'Swipper', label: '幻灯片管理' }
                - { entity: 'Region', label: '自定义区域' }
            - label: '用户管理'
              children:
                - {entity: 'User', label: '管理员'}
                - {entity: 'Provider', label: '商家'}
                - {entity: 'Member', label: '会员'}