easy_admin:
    entities:
        Category:
            class: 'AppBundle\Entity\Category'
            label: '分类'
            form:
                fields:
                    - { property: 'name', label: '名称' }
                    - { property: 'description', label: '描述' }
            new:
                title: '添加%%entity_label%%'
            edit:
                title: '编辑%%entity_label%%'
            list:
                title: '%%entity_label%%列表'