easy_admin:
    entities:
        Company:
            class: 'AppBundle\Entity\Company'
            label: '品牌信息'
            disabled_actions: ['list']
            form:
                fields:
                    - { property: 'title', label: '标题' }
                    - { property: 'imageFile', label: '标题图片', type: 'vich_image' }
                    - { property: 'content', label: '内容', type: 'ckeditor' }
            list:
                title: '%%entity_label%%列表'
                fields:
                    - { property: 'title', label: '标题' }
                    - { property: 'image', label: '标题图片', type: 'image', base_path: '%app.path.product_images%' }
                    - { property: 'content', label: '内容' }
                actions:
                    - '-new'
                    - '-delete'
            new:
                title: '添加%%entity_label%%'
            edit:
                title: '修改%%entity_label%%'
                actions:
                    - '-delete'