easy_admin:
    entities:
        Contact:
            class: 'AppBundle\Entity\Contact'
            label: '联系信息'
            form:
                fields:
                    - { property: 'title', label: '标题' }
                    - { property: 'content', label: '详细联系方式', type: 'ckeditor' }
            list:
                title: '%%entity_label%%列表'
            new:
                title: '添加%%entity_label%%'
            edit:
                title: '修改%%entity_label%%'