easy_admin:
    entities:
        Contact:
            class: 'AppBundle\Entity\Contact'
            label: '联系信息'
            form:
                fields:
                    - { property: 'companyName', label: '公司名称' }
                    - { property: 'address', label: '地址' }
                    - { property: 'tel', label: '固定电话' }
                    - { property: 'phone', label: '手机' }
                    - { property: 'email', label: '邮箱' }
                    - { property: 'weibo', label: '微博' }
                    - { property: 'qq', label: 'QQ' }
                    - { property: 'wechat', label: '微信' }
            list:
                title: '%%entity_label%%列表'
                fields:
                    - { property: 'companyName', label: '公司名称' }
                    - { property: 'address', label: '地址' }
                    - { property: 'phone', label: '手机' }
            new:
                title: '添加%%entity_label%%'
            edit:
                title: '修改%%entity_label%%'