easy_admin:
    entities:
        Goods:
            class: 'AppBundle\Entity\Goods'
            label: '已付款订单'
            form:
                fields:
                    - { property: 'tradeNo', label: '编号' }
                    - { property: 'subject', label: '订单名称' }
                    - { property: 'totalAmount', label: '总金额' }
                    - { property: 'couponId', label: '优惠券', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Coupon' } }
                    - { property: 'description', label: '订单描述' }
                    - { property: 'goodsDetail', label: '商品详情', type: 'easyadmin_autocomplete', type_options: { class: 'AppBundle\Entity\Product' } }
            list:
                title: '%%entity_label%%列表'
                dql_filter: 'entity.status = 1'
                actions:
                    - { name: 'show', label: '查看', icon: 'eye' }
                    - { name: 'paid', label: '已付款', icon: 'eye' }
                    - '-new'
                    - '-edit'
                    - '-delete'
                fields:
                    - { property: 'tradeNo', label: '编号' }
                    - { property: 'subject', label: '订单名称' }
                    - { property: 'totalAmount', label: '总金额' }
                    - { property: 'user', label: '消费者' }
                    - { property: 'createdAt', label: '购买时间' }
            show:
                title: '查看%%entity_label%%'
                actions:
                    - { name: 'send', label: '发货' }
                    - '-edit'
                    - '-delete'

                fields:
                    - { property: 'tradeNo', label: '编号' }
                    - { property: 'totalAmount', label: '总金额' }
                    - { property: 'subject', label: '订单名称' }
                    - { property: 'totalAmount', label: '总金额' }
                    - { property: 'address', label: '地址'}
                    - { property: 'goodsDetail', label: '商品详情', template: 'easy_admin/fields/good_details.html.twig' }
                    - { property: 'user', label: '消费者' }
                    - { property: 'createdAt', label: '购买时间' }
                    - { property: 'description', label: '备注' }