easy_admin:
    entities:
        Member:
            class: 'AppBundle\Entity\User'
            label: '会员'
            list:
                title: '%%entity_label%%列表'
                dql_filter: "entity.roles = 'a:0:{}'"
                fields:
                    - {property: 'username', label: '姓名'}
                    - {property: 'email', label: '邮箱'}
                    - {property: 'phone', label: '电话'}
                    - {property: 'enabled', label: '激活'}
                    - {property: 'birthday', label: '生日'}
                    - {property: 'sex', label: '性别'}
                    - {property: 'address', label: '地址'}
            form:
                fields:
                    - { type: 'tab', label: '基本信息'}
                    - { property: 'username', label: '用户名', css_class: 'col-sm-4' }
                    - { property: 'email', label: '邮箱', css_class: 'col-sm-4', css_class: 'col-sm-4'   }
                    - { property: 'role', label: '角色', css_class: 'col-sm-4' , type: 'choice', type_options: {choices:  {'普通用户': 'ROLE_USER', '供应商': 'ROLE_PROVIDER' , '超级管理员': 'ROLE_SUPER_ADMIN'}, placeholder: '请选择角色', data: 'ROLE_USER'  }}
                    - { property: 'phone', label: '电话', css_class: 'col-sm-4' }
                    - { property: 'sex', label: '性别', css_class: 'col-sm-4' , type: 'choice', type_options: { choices: {'男': '男', '女': '女'}, placeholder: '请选择性别' } }
                    - { property: 'address', type: 'AppBundle\Form\Type\AddressType', label: '请填写地址信息' }
                    - { type: 'group', label: '修改密码' }
                    - { property: 'plainPassword', label: '密码', type: 'repeated', type_options: { type: 'Symfony\Component\Form\Extension\Core\Type\PasswordType', first_options: { label: '密码'},second_options: {label : '重复密码'} ,invalid_message: '密码是必须要填写的' } }

                    - { type: 'tab', label: '体型数据'}
                    - { property: 'shape', label: '添加体型数据', type: 'AppBundle\Form\Type\ShapeType'}
                form_options: { validation_groups: ['Profile'] }
            new:
                title: '添加%%entity_label%%'
                fields:
                    - { property: 'plainPassword', type_options: { 'label_attr': {'class': required} } }
                form_options: { validation_groups: ['Registration'] }
            edit:
                title: '编辑%%entity_label%%'
                fields:
                    - { property: 'plainPassword', required: false }

