easy_admin:
    entities:
        Provider:
            class: 'AppBundle\Entity\User'
            label: '商家'
            list:
                dql_filter: " entity.roles = 'a:1:{i:0;s:13:\"ROLE_PROVIDER\";}'"
                title: '%%entity_label%%列表'
                fields:
                    - {property: 'username', label: '姓名'}
                    - {property: 'email', label: '邮箱'}
                    - {property: 'phone', label: '电话'}
                    - {property: 'sex', label: '性别'}
                    - {property: 'address', label: '地址'}
            form:
                fields:
                    - { property: 'username', label: '用户名' }
                    - { property: 'email', label: '邮箱' }
                    - { property: 'role', label: '角色', type: 'choice', type_options: {choices:  {'普通用户': 'ROLE_USER', '供应商': 'ROLE_PROVIDER' , '超级管理员': 'ROLE_SUPER_ADMIN'}, placeholder: '请选择角色', data: 'ROLE_PROVIDER'  }}
                    - { property: 'phone', label: '电话'}
                    - { property: 'sex', label: '性别', type: 'choice', type_options: { choices: {'男': '男', '女': '女'}, placeholder: '请选择性别' } }
                    - { property: 'plainPassword', label: '密码', type: 'password', required: true }
                    - {property: 'address', label: '地址'}
                form_options: { validation_groups: ['Profile'] }
            new:
                title: '添加%%entity_label%%'
                fields:
                    - { property: 'plainPassword', type_options: { 'label_attr': {'class': required} } }
                form_options: { validation_groups: ['Registration'] }
            edit:
                title: '编辑%%entity_label%%'
                fields:
                    - { property: 'plainPassword', required: false }