easy_admin:
    entities:
        Provider_Product:
            class: 'AppBundle\Entity\Product'
            label: '服装'
            form:
                fields:
                    - { type: 'tab', label: '基本信息', css_class: 'col-sm-10 col-offset-1'}
                    - { property: 'productNo', label: '编号', css_class: 'col-sm-6' }
                    - { property: 'title', label: '名称',css_class: 'col-sm-6' }
                    - { property: 'productType', label: '类型',css_class: 'col-sm-6' }
                    - { property: 'model', label: '版型',css_class: 'col-sm-6' }
                    - { property: 'stock', label: '数量',css_class: 'col-sm-6' }
                    - { property: 'supplyPrice', label: '供应价',css_class: 'col-sm-6' }
                    - { property: 'size', label: '尺码', css_class: 'col-sm-6' }
                    - { property: 'category', label: '分类', type: 'AppBundle\Form\Type\CategoryType',css_class: 'col-sm-6'  }
                    - { property: 'cycle', label: '制作周期', type: 'date'}
                    - { property: 'isFront', label: '推荐到首页' }
                    - { property: 'imageFile', label: '图片', type: 'vich_image' }
                    - { property: 'description', label: '详细信息', type: 'ckeditor' }
                    - {type: 'tab', label: '详细参数', css_class: 'col-sm-10 col-offset-1'}
                    - {property: 'articleNumber', label: '货号', css_class: 'col-sm-6'}
                    - {property: 'style', label: '款式', css_class: 'col-sm-6'}
                    - {property: 'styles', label: '风格', css_class: 'col-sm-6'}
                    - {property: 'material', label: '材质', css_class: 'col-sm-6'}
                    - {property: 'color', label: '颜色', css_class: 'col-sm-6'}
                    - {property: 'pattern', label: '图案', css_class: 'col-sm-6'}
                    - {property: 'thick', label: '薄厚', css_class: 'col-sm-6'}
                    - {property: 'craft', label: '工艺', css_class: 'col-sm-6'}
                    - {property: 'coatLength', label: '衣长', css_class: 'col-sm-6'}
                    - {property: 'sleeveLength', label: '袖长', css_class: 'col-sm-6'}
                    - {property: 'sleeveStyle', label: '袖型', css_class: 'col-sm-6'}
                    - {property: 'collarStyle', label: '领型', css_class: 'col-sm-6'}
                    - {property: 'flap', label: '衣门襟', css_class: 'col-sm-6'}
                    - {property: 'forking', label: '开叉', css_class: 'col-sm-6'}
                    - {property: 'flapStyle', label: '襟型', css_class: 'col-sm-6'}
                    - {property: 'pantsLength', label: '裤长', css_class: 'col-sm-6'}
                    - {property: 'skirtLength', label: '裙长', css_class: 'col-sm-6'}
                    - {property: 'skirtStyle', label: '裙型', css_class: 'col-sm-6'}
                    - {property: 'marketTime', label: '上市时间',type: 'date'}
            list:
                title: '%%entity_label%%列表'
                fields:
                    - { property: 'productNo', label: '编号' }
                    - { property: 'model', label: '型号' }
                    - { property: 'title', label: '名称' }
                    - { property: 'image', label: '图片',type: 'image', base_path: '%app.path.product_images%' }
                    - { property: 'stock', label: '库存' }
            new:
                title: '添加%%entity_label%%'
            edit:
                title: '修改%%entity_label%%'
            show:
                title: '%%entity_label%%'