easy_admin:
    entities:
        RetrunBackTrade:
            class: 'AppBundle\Entity\Goods'
            label: '退款订单'
            list:
                title: '%%entity_label%%列表'
                dql_filter: 'entity.status = 3'
                actions:
                    - { name: 'show', label: '查看', icon: 'eye' }
                    - '-new'
                    - '-edit'
                    - '-delete'
                fields:
                    - { property: 'tradeNo', label: '编号' }
                    - { property: 'subject', label: '订单名称' }
                    - { property: 'totalAmount', label: '总金额' }
                    - { property: 'user', label: '消费者' }
                    - { property: 'createdAt', label: '购买时间' }
            show:
                title: '查看%%entity_label%%'
                actions: ['-edit','-delete']
                fields:
                    - { property: 'tradeNo', label: '编号' }
                    - { property: 'totalAmount', label: '总金额' }
                    - { property: 'subject', label: '订单名称' }
                    - { property: 'totalAmount', label: '总金额' }
                    - { property: 'description', label: '订单描述' }
                    - { property: 'address', label: '地址'}
                    - { property: 'goodsDetail', label: '商品详情', template: 'fields/good_details.html.twig' }
                    - { property: 'user', label: '消费者' }
                    - { property: 'createdAt', label: '购买时间' }