easy_admin:
    entities:
        User:
            label: '网站用户'
            class: 'AppBundle\Entity\User'
            list:
                title: '%%entity_label%%列表'
                dql_filter:  "entity.roles = 'a:1:{i:0;s:16:\"ROLE_SUPER_ADMIN\";}'"
                actions:
                    - { name: 'new', label: '添加用户'}
                fields:
                    - { property: 'username', label: '用户名'}
                    - { property: 'email', label: '邮箱'}
                    - { property: 'phone', label: '电话'}
                    - { property: 'lastLogin', label: '最后登录时间'}
            form:
                fields:
                    - { type: 'tab', label: '基本信息'}
                    - { property: 'username', label: '用户名' }
                    - { property: 'companyName', label: '公司名称'}
                    - { property: 'email', label: '邮箱',type_options:{required: false} }
                    - { property: 'phone', label: '电话' }
                    - { property: 'plainPassword', label: '密码', type: 'repeated', type_options: { type: 'Symfony\Component\Form\Extension\Core\Type\PasswordType', first_options: { label: '密码'},second_options: {label : '重复密码'},invalid_message: '密码是必须要填写的' } }
                    - { property: 'role', label: '角色', type: 'choice', type_options: {choices:  {'普通用户': 'ROLE_USER', '供应商': 'ROLE_PROVIDER' ,'管理员': 'ROLE_ADMIN', '超级管理员': 'ROLE_SUPER_ADMIN'}, placeholder: '请选择角色',  required: true} }
                    - { property: 'birthday', label: '生日',type: 'birthday' }
                    - { property: 'sex', label: '性别', type: 'choice', type_options: { choices: {'男': '男', '女': '女'}, placeholder: '请选择性别' } }
                    - { property: 'address',  label: '地址', type: 'AppBundle\Form\Type\AddressType', type_options:{required: true, data_class: 'AppBundle\Entity\Address'}}
            new:
                title: '添加%%entity_label%%'
                role: ROLE_ADMIN
                fields:
                    - { property: 'plainPassword', type_options: { 'label_attr': {'class': required}, required: true} }
                    - { property: 'role', label: '角色', type: 'choice', type_options: {choices:  {'普通用户': 'ROLE_USER', '供应商': 'ROLE_PROVIDER' ,'管理员': 'ROLE_ADMIN', '超级管理员': 'ROLE_SUPER_ADMIN'}, placeholder: '请选择角色',data: '请选择角色',  required: true} }
            edit:
                title: '编辑%%entity_label%%'
                role: ROLE_ADMIN
                fields:
                    - { property: 'email', label: '邮箱',type_options:{required: false} }
                    - { property: 'plainPassword', required: false }
                    - { property: 'address', required: false }
                    - '-role'
            profile:
                title: '%%entity_label%%列表'
                role: IS_AUTHENTICATED_FULLY
                actions:
                    - { name: 'edit', label: '编辑' }
