easy_admin:
    entities:
        User:
            label: '网站管理员'
            class: 'AppBundle\Entity\User'
            list:
                title: '%%entity_label%%列表'
                dql_filter:  "entity.roles = 'a:1:{i:0;s:16:\"ROLE_SUPER_ADMIN\";}'"
                fields:
                    - { property: 'username', label: '用户名'}
                    - { property: 'email', label: '邮箱'}
                    - { property: 'phone', label: '电话'}
                    - { property: 'lastLogin', label: '最后登录时间'}
            form:
                fields:
                    - { property: 'username', label: '用户名' }
                    - { property: 'email', label: '邮箱',type_options:{required: false} }
                    - { property: 'phone', label: '电话' }
                    - { property: 'plainPassword', label: '密码', type: 'repeated', type_options: { type: 'Symfony\Component\Form\Extension\Core\Type\PasswordType', first_options: { label: '密码'},second_options: {label : '重复密码'} } }
                    - { property: 'role', label: '角色', type: 'choice', type_options: {choices:  {'普通用户': 'ROLE_USER', '供应商': 'ROLE_PROVIDER' , '超级管理员': 'ROLE_SUPER_ADMIN'}, placeholder: '请选择角色', data: 'ROLE_SUPER_ADMIN'  }}
            new:
                title: '添加%%entity_label%%'
                role: ROLE_ADMIN
            edit:
                title: '编辑%%entity_label%%'
                role: ROLE_ADMIN
            profile:
                title: '%%entity_label%%列表'
                role: IS_AUTHENTICATED_FULLY
                actions:
                    - { name: 'edit', label: '编辑' }
